### PR TITLE
Vectorize methods for lsst sims/150917

### PR DESCRIPTION
**Pull request by danielsf**
This pull request adds "vectorized" versions of the following methods (i.e. methods that can input and output numpy arrays)

palRefv -- adjust a cartesian vector for refraction
palRefro -- refraction for optical bands as a function of zenith distance
palPcd -- calculate a pincushion/barrel distortion
palUnpcd -- remove a pincushion/barrel distortion
palDbear -- find the angle between points on a sphere
palDaf2r -- convert degrees, min, sec to radians
palDav2m -- convert cartesian to spherical coordinates
palDcc2s -- convert spherical coordinates to direction cosines
palDd2tf -- convert days to hours, minutes, seconds
palDpav -- the bearing of one celestial object with respect to another
palDr2af -- convert radians to degrees, minutes, seconds
palDr2tf -- convert radians to hours, minutes, seconds
palDranrm -- normalize an angle to the range 0 to 2pi
palDsepv -- angle between two vectors
palDtf2d -- convert hours, minutes, seconds to days
palDtf2r -- convert hours, minutes, seconds to radians
palEpj -- convert MJD to Julian Epoch
palEpj2D -- convert Julian Epoch to MJD
palFk5hz -- convert FK5 position to Hipparcos position
palHfk5hz -- convert Hipparcos position to FK5 position
palOapqk -- observed place to apparent place (quick)
palMap -- mean position to geocentric apparent position
palGe50 -- Galactic coordinates to B1950 Fk4 coordinates
palGalsup -- galactic coordinates to supergalactic coordinates
palSupgal -- supergalactic coordinates to galactic coordinates
palFk524 -- FK5 position to FK4 position
palFK54z -- ditto, assuming no parallax or proper motion
palFK45z -- FK4 to FK5 without parallax or proper motion
palEqecl -- equatorial to ecliptic coordinates
palEcleq -- ecliptic to equatorial
palDtps2c -- RA, Dec from tangent plane
palDtp2s -- tangent plane to spherical coordinates
palDrange -- normalize an angle to the range -pi to pi
palDmoon -- geocentric position and velocity of the moon
palDjcal -- convert MJD to Gregorian calendar
palDh2e -- horizon to equatorial coordinates
palCaldj -- Gregorian calendar to MJD
palAmpqk -- quick geocentric apparent to mean place
palAirmas -- calculate airmass from zenith distance

It also adds a unit test for Fk524 based on data from the Explanatory Supplement to the Astronomical Almanac

It also updates all of the previously vectorized methods so that their docstrings are more explanatory and so that they raise exceptions when they are given nonsense inputs (i.e. numpy arrays of mismatched sizes).

If this gets merged, could you please tag a new version so that I can incorporate these vectorized methods into the LSST Sims stack?  Thank you.

### CODE REVIEW

**Comment by timj** [comment]
Thanks. This is impressive.

I have a couple of comments. Firstly this doesn't seem to work on python 3:
```
>       self.assertEqual(context.exception.message,
                         "You did not pass the same number of x as y " \
                         + "coordinates to unpcdVector")
E       AttributeError: 'ValueError' object has no attribute 'message'
```

Secondly, and I'm happy to defer this, I'd really prefer it if the vectorization routines used the modern cython memoryview syntax. This is a lot richer and flexible syntax and doesn't restrict the inputs to numpy. It also seems that the GIL can be disabled if we do that and that memoryviews are generally faster than numpy.

See http://docs.cython.org/src/userguide/memoryviews.html

**Comment by timj** [comment]
One final thought, looking back at the error message, why do we need to ensure that the error message of the exception raised exactly matches a string in the test?

**Comment by danielsf** [comment]
I check the content error messages in the unit test just to make sure that I haven't accidentally caused the routine to throw an exception for some other, unintended reason.

I will look into why the context.exception.message formalism does not work in python 3 and replace it with something that does.

I think I would prefer to make the transition to memory views a different pull request (which I am willing to work on).  There are some things in the sims stack I need to implement that require there be some vectorized version of these routines in place.

**Comment by danielsf** [comment]
I found a fix to the exception.message problem.  That same information is stored in exception.args[0].  I have pushed  a fix.

**Comment by timj** [comment]
I still worry about the fragility of error message checking and am nervous about the content being part of the interface. The point of exceptions is for us to be able to avoid that sort of thing. I think I'd be happier if palpy defined subclasses of `ValueError` for specific cases if you were concerned that a particular failure mode gave a particular problem (`DimensionsMismatchError` seems plausible, not sure if it needs PAL in front of it). Since it would subclass `ValueError` most people wouldn't have to notice the difference.

I won't hold the merge up on the memory view issue. It's great if you would look at that in the future though.

**Comment by danielsf** [comment]
Sub-classing ValueError seems like it might be overkill for this case.  I will change the unit test so that it just verifies that a ValueError is raise, without checking the message.  I'll let you know when I push that change.

**Comment by danielsf** [comment]
pushed

**Comment by danielsf** [comment]
Also: do I need to do something in this repo to reflect the fact that PAL should be cloned from a new commit (the change to 'tiny' that I sent you yesterday), or is that handled automatically by github?

**Comment by timj** [comment]
PAL is in a submodule, the submodule needs to be updated and then committed in the parent. I was going to do that update after I merged this PR.

**Pull request merged**
