### PR TITLE
Update pal to v0.9.4

### PR DESCRIPTION
**Pull request by timj**

### CODE REVIEW

**Comment by timj** [comment]
@danielsf can you please take a look? Tests are failing because one of your mapqk vector tests no longer works. If you can come up with a fix that would be great. The new `mapqk` test got rewritten a bit (and I need to go back and make the same fixes in PAL to use `palDafin`).

**Comment by danielsf** [comment]
The problem is that the PR

https://github.com/Starlink/pal/pull/11

added light deflection due to the sun to mapqkz, but not ampqk, which is nominally the inverse of mapqkz.  I will look into whether or not it is straightforward to update ampqk and issue another PR against PAL.

**Comment by danielsf** [comment]
The word from Patrick is that light deflection should have been in ampqk, and actually is in the latest version of SLALIB.  I will open the new PR in PAL

**Comment by timj** [comment]
Wow. Yes, just looked at SLALIB and it seems that we missed an entire block when the C PAL version was ported over by @dsberry. I have the fortran code here so I'll add it back into PAL.

**Comment by danielsf** [comment]
Okay.  Thanks.  I will not issue my PR.

Is it worth budgeting someone's time to go over all of the PAL methods, comparing to their most up-to-date SLALIB counterparts, and making sure there aren't any other surprises waiting for us?  I can probably write that off as my "level of effort CatSim maintenance" work for LSST.

**Comment by timj** [comment]
Regarding the audit, PAL was forked after most of the GPL SLALIB was written and I've tracked the minor upstream changes. We don't get any visibility into the C proprietary SLALIB of course. I'm a bit shocked that that chunk of code was missing from PAL and I don't really understand how we managed to miss it (I know when I ported files over I copied the Fortran directly into the C file, changed case everywhere and then fixed it all up). I'm not saying that an audit won't find anything of course, but I can't promise it's a productive use of your time (you could look at the change history and see which files were ported by other people as they may have used a different porting technique to mine). A somewhat more productive endeavor would be to look at ERFA/SOFA since PAL was created, to see if more code can be removed from PAL and replaced with routines that SOFA have added recently.

**Pull request merged**
